_data/homepage.yml
_information-for-regulated-dealers/1-list-of-registered-dealers.md
_information-for-regulated-dealers/3-guidance-materials.md
_information-for-regulated-dealers/4-key-resources.md
events/past-events/_posts/2019-05-28-onboarding-conferences.md

Added new URL from FATF guide
Added 's' to suppression (spelling mistake)
Reordered language for registration brochure (eng first)

Added FATF guide for PSPM

---

_data/homepage.yml
events/notices/_posts/2019-04-30-guidelines-for-regulated-dealers-issued-on-30-april-2019.md
events/notices/index.html
events/upcoming-events/_posts/Induction Briefing

All other commits were removed

Adding Notice as per Dir's feedback

---

_information-for-regulated-dealers/0-registration.md

Change "apply for registration" to "be registered"

---

_data/homepage.yml
_information-for-regulated-dealers/0-registration.md
_information-for-regulated-dealers/2-reg-compliance.md
misc/custom.scss

Added anchoring to reg page and reg comply page
Colour change at resource room
12days

12days + anchoring + colour change

---

_data/homepage.yml
_information-for-regulated-dealers/0-registration.md
index.md

added new key highlights: notices
5 days

5 days + key highlights: notices

---

_data/homepage.yml
_data/navigation.yml
_information-for-regulated-dealers/6-compliance-review-programme.md

Changes made on 13 Jan:
1. Added CRP tab
2. Placed CRP at front page, shifted Reg Compliance to 4 button section and removed "Notices"
3. Updated IB chinese slides ("FA AN" to "FA LING")

CRP + IB slides

---

news/ongoing-events/_posts/2019-11-28-Onboarding-Workshops-for-Compliance-Officer.md

from "to sign up" to "to indicate your interest"

Changed wording for 2nd last sentence

---

_regulated-dealers/1-registration.md
_regulated-dealers/2-renewal.md

Changed "Nationality/ Country of Incorporation" to "Citizenship or Country/ Region of Incorporation" x3 each page

Change Registration and Renewal page

---

_regulated-dealers/1-registration.md
index.md
news/ongoing-events/_posts/2019-11-28-Onboarding-Workshops-for-Compliance-Officer.md

Registration page: Inserted new liner: Foreign dealers may refer [here](/regulatory-regime/#Regulatory%20Compliance%20for%20Foreign%20Dealers/) on the requirements to register.
Red banner: Updated to Update: Onboarding Workshop is now conducted ONLINE!
OBW page:
1. Inserted new liner: OBW is now conducted online. and removed "in the upcoming months." in first para.
2. Updated link to form: https://go.gov.sg/onlineonboardingworkshop
3. Updated "workshop" to "OBW" x2

Multiple changes on OBW and foreign dealer

---

_compliance/3.5-common-offences-under-the-pspm-act

Removed 'common offences under PSPM Act' -> this was meant for testing purposes only

Pull request for 20 Jul

---

_data/navigation.yml
news/upcoming-events/_posts/2020-07-21-compliance-training.md
news/upcoming-events/_posts/compliance-training.md

1. Created "Upcoming Events" tab under News category
2. Added message for Compliance Training under Upcoming Events

Updates for 21 Jul

---

_data/homepage.yml
_regulated-dealers/3-list-of-registered-dealers.md
index.md

-Update content on List of Registered Dealers page to include comments on Investment products
-Update red banner to link to List of Registered Dealers page
-Update brown button from "Registration" to "Renewal"

Pull Request for 21 Aug 

---

_data/navigation.yml

Populated dropdown for "Regulation" tab.
Changes performed on _data -> navigation.yml folder.

19 Oct- Updated navigation panel on home page

---

_regulated-dealers/6-e-services.md

1. added myPal as an e-services under Regulated Dealers -> E-services tab.

Pull Request for 19 May 2021

---

news/past-events/_posts/2021-04-12-online-training-on-submission-of-semi-annual-returns.md

Pull Request for 8 Jun 2021:
Amendment of word from "demo video" to "guidance video":
from:
Please stay tuned to our website for the upcoming semi-annual return instruction guide and demo video!
to:
Please stay tuned to our website for the upcoming semi-annual return instruction guide and guidance video!

Amend Sign Up For Online Training On Submission Of Semi-Annual Returns section

---

_compliance/0-entity-based-requirements.md
_regulated-dealers/5-guidance-materials.md
_regulation/1-guidance-papers.md
index.md

Pull request for 15 Jul 2021:
1) Add DIT 2.0 video on "How to perform risk assessment and develop your IPPC" on 1) Compliance > Entity-Based Requirements page, 2) Reglated Dealers > Guidance Materials > "9. Videos and Posters" section
2) Shift sequence of the video under section "9. Videos and Posters" -
Shifted "Video: Submission of Semi-Annual Return using myPal" semi-annual return video and "Video: How to perform risk assessment and develop internal policies, procedures and controls ("IPPC")" to be the first and second video respectively under section "9. Videos and Posters" as it is easier to direct dealers to refer to the videos
3) Amend red banner 
from: "Sign up for Guidance Paper briefing now!",
to: "How to perform risk assessment and internal policies, procedures and controls …

Upload DIT 2.0 video - How to perform risk assessment and develop IPPC + Amend red banner

---

news/past-events/_posts/2021-04-12-online-training-on-submission-of-semi-annual-returns.md

to remove "Sign Up For" wording, 
from:
title: 'Sign Up For Online Training On Submission Of Semi-Annual Returns'
to:
title: 'Online Training On Submission Of Semi-Annual Returns'

Amend Semi-Annual Return title

---

_regulated-dealers/1-registration.md
_regulated-dealers/3-renewal.md

Pull request for 30 Jul 20201:
Amend all mention of Corppass and Singpass (with small letter ‘p’) under 'Registration' and 'Renewal' section, due to Singpass and Corppass brand refresh (as advised by ITD)

Update references for Corppass and Singpass under Registration

---

_compliance/4-compliance-review-programme.md

Pull Request for 2 Sep 2021

---

_compliance/2-other-regulatory-requirements.md

1. removed a typo 'amend' under Line 29 of the PDF file

Pull Request for 20 Sep 2021

---

index.md

1. Amended red banner message from Compliance Training to GoBusiness maintenance

Pull request for 4 Oct 2021

---

_compliance/4-compliance-review-programme.md

Second pull request for 1 Dec 2021

---

_compliance/4-compliance-review-programme.md
news/past-events/_posts/2020-07-21-compliance-training.md

1. Added 1 reviewer name in CRP page
2. Shifted Compliance Training to past event section

Pull request for 8 Dec 2021

---

index.md

Amend wordings in red banner and link to list of registered dealers' page.

Pull request for 20 Jan 2022

---

news/ongoing-events/_posts/2202-02-15-post-skillsfuture-fellowships-and-skillsfuture-employer-awards-2022.md

Update: SSG SkillsFuture Fellowships & SkillsFuture Employer Awards 2022 application window closing date from 21 March 2022 to 28 March 2022

---

news/notices-from-the-registrar/_posts/2022-06-21-post-Call for Action in Accordance with June 2022 FATF Statement.md

Pull Request for 21 Jun 2022

---

index.md

Red banner: Changed from March 2022 to June 2022 FATF statement
Red button: Changed from “Guidance material….” to “Submit SAR”

Updates to "red banner" and "red button" on homepage

---

index.md

Update of mainpage red banner "Download and use the Compliance Toolkit now!".

30 September 2022 - Update of red banner

---

index.md

Update of Red Banner - (Latest!) October 2022 FATF Public Statement - Jurisdictions with Strategic Deficiencies and what you should know when dealing with Myanmar

9 November 2022 - Update of red banner

---

_compliance/compliance-review-programme.md

• Addition of 1 reviewer name - 4. Anton Ranil Amarasiri

Update: Addition of 1 reviewer name under Compliance: Compliance Review Programme

---

_compliance/compliance-review-programme.md

Added:
Lim Kah Sim
Tan Wei Qi
Tricia Toh
Yip Seow Wei

Addition of 3 reviewer names AND formatted existing reviewer names under Compliance: Compliance Review Programme 

---

index.md

Changed from "GUIDANCE PAPER FOR REGULATED DEALERS" to "SUBMIT SEMI-ANNUAL RETURN VIA MYPAL"

Updated Red Button on homepage 

---

_compliance/compliance-review-programme.md
index.md

1. Added name of 1 new CRP reviewer 
2. Updated red button to "Compliance Toolkit for PSMD"
3. Updated red banner to "Download and use the Compliance Toolkit now!"

23 Feb 2023 website updates

---

news/notices-from-the-registrar/_posts/2022-09-30-post-Compliance Toolkit for Precious Stones and Precious Metals Dealers.md

Update of broken link of Compliance Toolkit for Precious Stones and Precious Metals Dealers 30 SEP 2022 under Notices from the Registrar.

Broken link for Compliance Toolkit

---

index.md

Images not shown properly for:
1. 'Fulfil Entity-Based Requirements' & 2. 'Learn from guidance videos'

Fixed: Broken images on homepage 

---

_compliance/offences-breaches-under-the-pspm-act-and-pmltf-regulations.md

-Updated section on CDSA under 'Compliance > Offences/Breaches under the PSPM Act and PMLTF Regulations'

Website update - 20 July 2023

---

pages/Compliance Review Programme Reviewers.md

Additions of 2 newly cleared reveiwers names as of 29 Aug 2023
3. Clifford Guok Khor Huat
9. Lim Siew Kim

Update Compliance Review Programme Reviewers as of 29 Aug 2023

---

pages/Compliance Review Programme Reviewers.md

Update list of reviewers by addition of 2 newly cleared names as of 7 Sep 2023
11. Mohan Srisuriya
12. Nicholas Koh Ngee Hao

Update list of reviewers as of 7 Sep 2023

---

_compliance/aml-cft-resources.md
news/ongoing-events/_posts/2020-10-08-post-financial-support-for-anti-money-launderingcountering-the-financing-of-terrorism-amlcft-screening-solutions.md
pages/Compliance Review Programme Reviewers.md

- Addition of 3 CRP reviewers as of 27 Sep 2023 (3. Choo, Yen Lin, 7. Kannan, Yegammai and 19. Wong, Andrew Yee Hern)
- Removal of "Financial support for precious stones and precious metals dealers on the purchase of pre-scoped AML/CFT screening solutions via the Productivity Solutions Grant (PSG)."

Website update as of 29 Sep 2023

---

news/notices-from-the-registrar/_posts/2023-11-01-post-Call for Action in Accordance with October 2023 FATF Statement.md

Added the following in **bold**:
"Accordingly, under regulation 7(1) of the Precious Stones and Precious Metals (Prevention of Money Laundering and Terrorism Financing) Regulations **2019**...."

Edits to 'October 2023 FATF Statement'

---

index.md

- Update red banner to Feb 2024 FATF Public Statement and insert the link

Update Red Banner as of 7 Mar 2024

---

_regulated-dealers/Regulation Coverage.md

Under Regulated Dealers > Regulation Coverage >  Investments are Not Covered Under the Regulations

Updated MoneySense links

---

_compliance/other-regulatory-requirements.md
_data/navigation.yml

Old link: https://console-flex-api.ap.sabio.cloud/faq/index.aspx?p=64759355
New link: https://console.apac.sabio.cloud/FAQ/index.aspx?p=64759355

Update of FAQ link - 20/9/2024

---

_regulated-dealers/list-of-registered-dealers.md
pages/Compliance Review Programme Reviewers.md

upload suspension/cancellation of registered dealers

Pull request for 15 Oct 2024 - 

---

news/notices-from-the-registrar/_posts/2024-11-05-post-Call for Action in Accordance with October 2024 FATF Statement.md

To publish the FATF October 2024 statement.

Website update - 5 Nov 2024

---

news/notices-from-the-registrar/_posts/2024-12-20-post-Amendments to Subsidiary Legislation under the PSPM Act with effect from 20 December 2024.md

- add the FAQ link to the Notices from the Registrar - Amendments to Subsidiary Legislation under the PSPM Act with effect from 20 December 2024

Update Website as of 23 Dec 2024

---

news/notices-from-the-registrar/_posts/2022-09-08-post-Launch of Screening Function in myPal.md

- fix broken FAQ link at News > Notices From The Registrar > Launch of Screening Function in myPal

Fix broken link

---

index.md
news/ongoing-events/_posts/2025-01-24-post-SkillsFuture Fellowships and SkillsFuture Employer Awards 2025.md

- Update the dead FAQ link for the SkillsFuture Empolyer Awards
- Update the Red Notification Banner to "SkillsFuture Fellowships and SkillsFuture Employer Awards 2025 (latest!)"

Further Website Update as of 24 Jan 25

---

index.md

- Revive the link for the red hero banner

Revive the link for the red hero banner 

---

news/enforcement/_posts/2025-06-19-post-Ministry of Law imposes Composition Sum on Singapore Precious Metals Exchange Pte Ltd and its CEO.md

- Amending paragraph 2 of the SPME publication

Website Update - Amendment of the SPME Publication

---

news/scam-advisories/_posts/2025-07-21-post-Detecting Government Official Impersonation Scam (GOIS) in Gold and Jewellery Transactions.md

- Remove the underline for the dates of the advisories in the published "Detecting Government Official Impersonation Scam (GOIS) in Gold and Jewellery Transactions".

Website Update as of 21 Jul 2025

---

pages/faq.md

- Update the new FAQ link "https://ask.gov.sg/mlaw" in ACD Website.

Website Update as of 27 Aug 2025
